### ISSUE TITLE
not working from virtualenv

### ISSUE THREAD

**Issue by kidpixo** [ellisonbg/ipyleaflet#29]
I'm under Mac OSX 10.10.5 and using python from macports.

I cannot get `ipyleaflet` works in a virtualenv created using the `--system-site-packages` keyword.

I suppose it is because the system `jupyter-s` subcommands search in their installation path and not in the one from `virtualenv`.

I'm not entirely sure if it is an issue to be open here or at [Issues · ipython-contrib/IPython-notebook-extensions](https://github.com/ipython-contrib/IPython-notebook-extensions/issues), maybe I'll open another one there.

Here the details:

Those are the version of `jupyter-s` stuff I'm using. (the pyXX prefix is used by macport to differenziate versions of the same command). 

```
  py27-ipywidgets @5.1.4_0 (active)
  py27-widgetsnbextension @1.2.2_0 (active)
  py27-widgetsnbextension @1.2.2_0 (active)
  py27-jupyter @1.0.0_1 (active)
  py27-jupyter_client @4.2.2_0 (active)
  py27-jupyter_console @4.1.1_0 (active)
  py27-jupyter_core @4.1.0_0 (active)
```

If I install `ipyleaflet` in a virtual env and activate it, I get 

```
jupyter nbextension enable --py ipyleaflet 

Traceback (most recent call last):
  File "/opt/local/bin/jupyter-nbextension", line 9, in <module>
    load_entry_point('notebook==4.2.0', 'console_scripts', 'jupyter-nbextension')()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/traitlets/config/application.py", line 596, in launch_instance
    app.start()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/notebook/nbextensions.py", line 952, in start
    super(NBExtensionApp, self).start()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jupyter_core/application.py", line 256, in start
    self.subapp.start()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/notebook/nbextensions.py", line 860, in start
    self.toggle_nbextension_python(self.extra_args[0])
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/notebook/nbextensions.py", line 836, in toggle_nbextension_python
    logger=self.log)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/notebook/nbextensions.py", line 459, in enable_nbextension_python
    logger=logger)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/notebook/nbextensions.py", line 374, in _set_nbextension_state_python
    m, nbexts = _get_nbextension_metadata(module)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/notebook/nbextensions.py", line 1114, in _get_nbextension_metadata
    m = import_item(module)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/traitlets/utils/importstring.py", line 41, in import_item
    return __import__(parts[0])
ImportError: No module named ipyleaflet
```

and `jupyter-nbextension list` gives 
```
Known nbextensions:
  config dir: /Users/kidpixo/.jupyter/nbconfig
    notebook section
      jupyter-js-widgets/extension  enabled
      - Validating: OK
      ipyleaflet  enabled
      - Validating: problems found:
        - require?  X ipyleaflet
```

If I install `ipyleaflet` globally everything is fine.

```
jupyter-nbextension list

Known nbextensions:
  config dir: /Users/kidpixo/.jupyter/nbconfig
    notebook section
      jupyter-leaflet/extension  enabled
      - Validating: OK
      jupyter-js-widgets/extension  enabled
      - Validating: OK
      ipyleaflet disabled
```

I'm still wondering why I have `jupyter-leaflet/extension` and `ipyleaflet` in my extensions...

**Comment by SylvainCorlay** [comment]
You probably have ipyleaflet in your extensions because you forgot the
`--py` in the enabling command at some point.

To enable ipyleaflet in a virtual environment you need to add the
--sys-prefix option to the extension enabling command.

Best

**Comment by kidpixo** [comment]
Thanks, I'm pretty sure I always used `--py`, but I'll check again.

I didn't get what is `--sys-prefix` exactly doing : it is installing as global ? 
if yes, what is the sense of use a virtualenv?

If I use `--sys-prefix` I end up having a `notebook.json` file in 

```
/opt/local/Library/Frameworks/Python.framework/Versions/2.7/etc/jupyter/nbconfig/
```
that apply to all the notebook I create system wide, I suppose.

**Comment by kidpixo** [comment]
Ok, 
if I use 
```
 sudo jupyter nbextension enable --sys-prefix ipyleaflet
```

I end up with 
```
jupyter nbextension  list

Known nbextensions:
  config dir: /opt/local/Library/Frameworks/Python.framework/Versions/2.7/etc/jupyter/nbconfig
    notebook section
      jupyter-js-widgets/extension  enabled
      - Validating: OK
      ipyleaflet  enabled
      - Validating: problems found:
        - require?  X ipyleaflet
```

So: it enabled  `ipyleaflet` system-wide, but it doesn't satisfy the dependencies, because it is installed in a virtualenv, am I right?

**Comment by SylvainCorlay** [comment]
I *think* that to use notebook extensions in virtual envs you will need to install the package and enable them while in the virtual env...
The `jupyter nbextension install --py --sys-prefix ipyleaflet` is unnecessary because the static assets are installed as data files of the wheel, already under sys-prefix.

**Comment by kidpixo** [comment]
That is from the global installlation of `ipyleaflet` :
```
/opt/local/Library/Frameworks/Python.framework/Versions/2.7/share/jupyter/nbextensions/jupyter-leaflet/index.js
```

that is from the virtualenv:

```
/Users/kidpixo/.virtualenvs/ipyleaflet/share/jupyter/nbextensions/jupyter-leaflet/index.js
```

now, looking at the jupyter data_dir ant paths:
``` 
ipython -c 'from jupyter_core.paths import jupyter_data_dir, jupyter_path; print jupyter_data_dir(); print jupyter_path()'

WARNING: Attempting to work in a virtualenv. If you encounter problems, please install IPython inside the virtualenv.

/Users/damo_ma/Library/Jupyter
['/Users/damo_ma/Library/Jupyter', 
'/opt/local/Library/Frameworks/Python.framework/Versions/2.7/share/jupyter', 
'/usr/local/share/jupyter', '/usr/share/jupyter']
```

and `/opt/local/.../jupyter/nbextensions/` is where actually the extentions are on my machine, in this particular case I have only `jupyter-js-widgets`, because it comes from system-wide macports installation.

Following [Paths for Jupyter files — jupyter_core 4.2.0.dev documentation](http://jupyter-core.readthedocs.io/en/latest/paths.html) I try to set `JUPYTER_PATH `, without luck.

**Comment by kidpixo** [comment]
## Update

**Dirty Workaround**

Based on previous test, I succeed creating a symlink 

```
sudo  ln -s \ 
/Users/kidpixo/.virtualenvs/ipyleaflet/share/jupyter/nbextensions/jupyter-leaflet/  \
/opt/local/Library/Frameworks/Python.framework/Versions/2.7/share/jupyter/nbextensions/jupyter-leaflet
```

Even if when enabling the extension jupyter trows an ImportError :  
```
jupyter nbextension enable --py pyleaflet
Traceback (most recent call last):
  File "/opt/local/bin/jupyter-nbextension", line 9, in <module>
    load_entry_point('notebook==4.2.0', 'console_scripts', 'jupyter-nbextension')()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/traitlets/config/application.py", line 596, in launch_instance
    app.start()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/notebook/nbextensions.py", line 952, in start
    super(NBExtensionApp, self).start()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jupyter_core/application.py", line 256, in start
    self.subapp.start()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/notebook/nbextensions.py", line 860, in start
    self.toggle_nbextension_python(self.extra_args[0])
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/notebook/nbextensions.py", line 836, in toggle_nbextension_python
    logger=self.log)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/notebook/nbextensions.py", line 482, in disable_nbextension_python
    logger=logger)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/notebook/nbextensions.py", line 374, in _set_nbextension_state_python
    m, nbexts = _get_nbextension_metadata(module)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/notebook/nbextensions.py", line 1114, in _get_nbextension_metadata
    m = import_item(module)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/traitlets/utils/importstring.py", line 41, in import_item
    return __import__(parts[0])ImportError: No module named pyleaflet
```

this results in a working enviroment and the extensions list seems sane:

```
jupyter nbextension list

Known nbextensions:
  config dir: /Users/damo_ma/.jupyter/nbconfig
    notebook section
      jupyter-leaflet/extension  enabled
      - Validating: OK
      jupyter-js-widgets/extension  enabled
      - Validating: OK
```

I don't understand a point anyway:  If import ipyleaflet in `jupyter console` or in `ipython` in the virtualenv it looks ok, I don't know why `jupyter nbextension` is complaining.

jupyter >

```
$ jupyter console

Jupyter Console 4.1.1
In [1]: import ipyleaflet; print ipyleaflet.__version__
0.2.0
```

ipython >

```
ipython -c 'import ipyleaflet; print ipyleaflet.__version__'

WARNING: Attempting to work in a virtualenv. If you encounter problems, please install IPython inside the virtualenv.
0.2.0
```
