### ISSUE TITLE
Ipywidget version supported

### ISSUE THREAD

**Issue by updiversity** [ellisonbg/ipyleaflet#52]
Hi,

I would like to know what are the ipywidget version supported as it looks that with the 6.0.0 it is not working.

**Comment by SylvainCorlay** [comment]
ipywidgets 5.x is suppoeted by the last stable release. ipywidgets 6.0 was released today.

I will release ipyleaflet tomorrow to officially support ipywidgets 6.0.

In the mean time you can either downgrade ipywidgets or run ipyleaflet from source.

**Comment by SylvainCorlay** [comment]
Actually, can you give more details about what you are seeing. In the classic notebook, this might work with ipywidgets 6.0.

**Comment by sergesvr** [comment]
Actually, this is what i got, when i try to install it

```
sudo jupyter nbextension enable --py --system ipyleaflet
```

```
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-nbextension", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/dist-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/usr/local/lib/python3.4/dist-packages/notebook/nbextensions.py", line 969, in start
    super(NBExtensionApp, self).start()
  File "/usr/local/lib/python3.4/dist-packages/jupyter_core/application.py", line 256, in start

    self.subapp.start()
  File "/usr/local/lib/python3.4/dist-packages/notebook/nbextensions.py", line 877, in start
    self.toggle_nbextension_python(self.extra_args[0])
  File "/usr/local/lib/python3.4/dist-packages/notebook/nbextensions.py", line 853, in toggle_nbextension_python
    logger=self.log)
  File "/usr/local/lib/python3.4/dist-packages/notebook/nbextensions.py", line 459, in enable_nbextension_python
    logger=logger)
  File "/usr/local/lib/python3.4/dist-packages/notebook/nbextensions.py", line 374, in _set_nbextension_state_python
    m, nbexts = _get_nbextension_metadata(module)
  File "/usr/local/lib/python3.4/dist-packages/notebook/nbextensions.py", line 1140, in _get_nbextension_metadata
    m = import_item(module)
  File "/usr/local/lib/python3.4/dist-packages/traitlets/utils/importstring.py", line 42, in import_item
    return __import__(parts[0])
  File "/usr/local/lib/python3.4/dist-packages/ipyleaflet/__init__.py", line 3, in <module>
    from .leaflet import *
  File "/usr/local/lib/python3.4/dist-packages/ipyleaflet/leaflet.py", line 12, in <module>
    from ipywidgets.widgets.interaction import _widget_from_abbrev
ImportError: cannot import name '_widget_from_abbrev'

```

**Comment by SylvainCorlay** [comment]
Thanks. This one is fixed in master indeed. I am AFK right now. releasing
tomorrow.

**Comment by SylvainCorlay** [comment]
@updiversity, ipyleaflet 0.3.0 has been released.
