### ISSUE TITLE
Unexpected token: punc (,) [./~/jupyter-leaflet/src/jupyter-leaflet.js:528,30]

### ISSUE THREAD

**Issue by stonebig** [ellisonbg/ipyleaflet#93]
I get this error when bulding jupyterlab on windows, not sure what to do about it.
For now, I'll remove ipyleaflet-1.0.0b3. Is there another suggestion ?

````
C:\winpython-64bit-3.6.x.0\scripts>jupyter labextension list
JupyterLab v0.31.0rc1
Known labextensions:
   app dir: C:\winpython-64bit-3.6.x.0\python-3.6.4.amd64\share\jupyter\lab
bqplot
        bqplot v0.3.2 enabled  ok
jupyter-leaflet
        jupyter-leaflet v0.5.1 enabled  ok
jupyter-matplotlib
        jupyter-matplotlib v0.3.0 enabled  ok
jupyter-threejs
        jupyter-threejs v0.4.1 enabled  ok

C:\winpython-64bit-3.6.x.0\scripts>jupyter lab clean

C:\winpython-64bit-3.6.x.0\scripts>"%WINPYDIR%\Scripts\jupyter.exe"  labextension install bqplot
> C:\winpython-64bit-3.6.x.0\python-3.6.4.amd64\..\tools\n\npm.CMD pack bqplot
bqplot-0.3.2.tgz
> node C:\winpython-64bit-3.6.x.0\python-3.6.4.amd64\lib\site-packages\jupyterlab\staging\yarn.js install
yarn install v1.3.2
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.1.3: The platform "win32" is incompatible with this module.
info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "@jupyterlab/json-extension > react-highlighter@0.4.2" has unmet peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".
warning "@jupyterlab/json-extension > react-json-tree@0.10.9" has unmet peer dependency "react@^15.0.0".
warning "@jupyterlab/json-extension > react-json-tree@0.10.9" has unmet peer dependency "react-dom@^15.0.0".
warning "@jupyterlab/vdom-extension > @nteract/transform-vdom@1.1.1" has unmet peer dependency "react@^15.6.1".
[4/4] Building fresh packages...
[-/3] ⠈ waiting...
[2/3] ⠈ canvas: not ok
[3/3] ⠈ jupyter-matplotlib
[-/3] ⠈ waiting...
warning Error running install script for optional dependency: "C:\\WinPython\\basedir36\\buildQt5\\winpython-64bit-3.6.x.0\\python-3.6.4.amd64\\share\\jupyter\\lab\\staging\\node_modules\\canvas: Command failed.\nExit code: 1\nCommand: node-gyp rebuild\nArguments: \nDirectory: C:\\WinPython\\basedir36\\buildQt5\\winpython-64bit-3.6.x.0\\python-3.6.4.amd64\\share\\jupyter\\lab\\staging\\node_modules\\canvas\nOutput:\nC:\\WinPython\\basedir36\\buildQt5\\winpython-64bit-3.6.x.0\\python-3.6.4.amd64\\share\\jupyter\\lab\\staging\\node_modules\\canvas>if not defined npm_config_node_gyp (node \"C:\\WinPython\\basedir36\\buildQt5\\winpython-64bit-3.6.x.0\\tools\\n\\node_modules\\npm\\bin\\node-gyp-bin\\\\..\\..\\node_modules\\node-gyp\\bin\\node-gyp.js\" rebuild )  else (node \"\" rebuild ) \r\ngyp info it worked if it ends with ok\ngyp info using node-gyp@3.4.0\ngyp info using node@6.11.5 | win32 | x64\ngyp ERR! configure error \ngyp ERR! stack Error: Python executable \"C:\\WinPython\\basedir36\\buildQt5\\winpython-64bit-3.6.x.0\\python-3.6.4.amd64\\python.EXE\" is v3.6.4, which is not supported by gyp.\ngyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.\ngyp ERR! stack     at failPythonVersion (C:\\WinPython\\basedir36\\buildQt5\\winpython-64bit-3.6.x.0\\tools\\n\\node_modules\\npm\\node_modules\\node-gyp\\lib\\configure.js:454:14)\ngyp ERR! stack     at C:\\WinPython\\basedir36\\buildQt5\\winpython-64bit-3.6.x.0\\tools\\n\\node_modules\\npm\\node_modules\\node-gyp\\lib\\configure.js:443:9\ngyp ERR! stack     at ChildProcess.exithandler (child_process.js:189:7)\ngyp ERR! stack     at emitTwo (events.js:106:13)\ngyp ERR! stack     at ChildProcess.emit (events.js:191:7)\ngyp ERR! stack     at maybeClose (internal/child_process.js:920:16)\ngyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:351:11)\ngyp ERR! stack     at emitOne (events.js:96:13)\ngyp ERR! stack     at Socket.emit (events.js:188:7)\ngyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:497:12)\ngyp ERR! System Windows_NT 10.0.16299\ngyp ERR! command \"C:\\\\WinPython\\\\basedir36\\\\buildQt5\\\\winpython-64bit-3.6.x.0\\\\python-3.6.4.amd64\\\\..\\\\tools\\\\n\\\\node.exe\" \"C:\\\\WinPython\\\\basedir36\\\\buildQt5\\\\winpython-64bit-3.6.x.0\\\\tools\\\\n\\\\node_modules\\\\npm\\\\node_modules\\\\node-gyp\\\\bin\\\\node-gyp.js\" \"rebuildsuccess Saved lockfile.
Done in 489.24s.
> node C:\winpython-64bit-3.6.x.0\python-3.6.4.amd64\lib\site-packages\jupyterlab\staging\yarn.js run build:prod
yarn run v1.3.2
$ webpack -p
Hash: 103b2a5117d8f0c79262
Version: webpack 2.7.0
Time: 110468ms
                                 Asset       Size  Chunks                    Chunk Names
  912ec66d7572ff821749319396470bde.svg     444 kB          [emitted]  [big]
  2273e3d8ad9264b7daa5bdbf8e6b47f8.png    1.47 kB          [emitted]
  6a1e950d14904d4b6fb5c9bdc3dfad06.png    3.58 kB          [emitted]
  deac1d4aa2ccf7ed832e4db55bb64e63.png    1.91 kB          [emitted]
  4f0283c6ce28e888000e978e537a6a56.png    1.26 kB          [emitted]
  a6137456ed160d7606981aa57c559898.png  696 bytes          [emitted]
  d95d69fa8a7dfe391399e22c0c45e203.png    2.59 kB          [emitted]
  44a526eed258222515aa21eaffd14a96.png  618 bytes          [emitted]
af7ae505a9eed503f8b8e6982036873e.woff2    77.2 kB          [emitted]
 fee66e712a8a08eef5805a46892932ad.woff      98 kB          [emitted]
  b06871f281fee6b241d60582ae9369b9.ttf     166 kB          [emitted]
  674f50d287a8c48dc19ba404d20fe713.eot     166 kB          [emitted]
             0.01bbce03dfb038fb4095.js     425 kB       0  [emitted]  [big]  vega2
             1.697f116e8467e0f2ccc6.js     422 kB       1  [emitted]  [big]
          main.a9060117c02afbdfe1f6.js    7.02 MB       2  [emitted]  [big]  main
        vendor.8111c5f9148384d98efc.js    1.48 MB       3  [emitted]  [big]  vendor
      manifest.d65e71dddccce81a5785.js    1.57 kB       4  [emitted]         manifest
         0.01bbce03dfb038fb4095.js.map     439 kB       0  [emitted]         vega2
         1.697f116e8467e0f2ccc6.js.map     452 kB       1  [emitted]
      main.a9060117c02afbdfe1f6.js.map    8.59 MB       2  [emitted]         main
    vendor.8111c5f9148384d98efc.js.map    1.53 MB       3  [emitted]         vendor
  manifest.d65e71dddccce81a5785.js.map    1.78 kB       4  [emitted]         manifest
                            index.html    1.71 kB          [emitted]
[+HaM] ./~/@phosphor/messaging/lib/index.js 18.5 kB {3} [built]
[2Kj9] ./~/@phosphor/widgets/lib/index.js 1.34 kB {3} [built]
[8U58] ./~/codemirror/lib/codemirror.js 352 kB {3} [built]
[CUbq] ./~/@phosphor/signaling/lib/index.js 18.1 kB {3} [built]
[GiK3] ./~/react/index.js 190 bytes {3} [built]
[O27J] ./~/react-dom/index.js 1.36 kB {3} [built]
[Vszx] ./~/@phosphor/domutils/lib/index.js 636 bytes {3} [built]
[cYMN] ./~/@phosphor/virtualdom/lib/index.js 21 kB {3} [built]
[lMhA] ./~/@phosphor/dragdrop/lib/index.js 33.7 kB {3} [built]
[nh00] ./~/@phosphor/disposable/lib/index.js 4.24 kB {3} [built]
[qzHn] ./~/@phosphor/coreutils/lib/index.js 721 bytes {3} [built]
[ug+F] ./~/xterm/lib/xterm.js 52.7 kB {3} [built]
   [5] multi @phosphor/algorithm @phosphor/application @phosphor/commands @phosphor/coreutils @phosphor/datagrid @phosphor/disposable @phosphor/domutils @phosphor/dragdrop @phosphor/messaging @phosphor/properties @phosphor/signaling @phosphor/virtualdom @phosphor/widgets ajv ansi_up codemirror comment-json es6-promise marked moment path-posix react react-dom sanitize-html url-parse xterm 328 bytes {3} [built]
   [6] multi whatwg-fetch ./build/index.out.js 40 bytes {2} [built]
[wr2+] ./~/@phosphor/properties/lib/index.js 6.58 kB {3} [built]
    + 1618 hidden modules

ERROR in main.a9060117c02afbdfe1f6.js from UglifyJs
Unexpected token: punc (,) [./~/jupyter-leaflet/src/jupyter-leaflet.js:528,30][main.a9060117c02afbdfe1f6.js:117674,32]
Child html-webpack-plugin for "index.html":
    [3IRH] (webpack)/buildin/module.js 517 bytes {0} [built]
    [DuR2] (webpack)/buildin/global.js 509 bytes {0} [built]
    [GTAU] ./~/html-loader!./templates/partial.html 401 bytes {0} [built]
    [M4fF] ./~/lodash/lodash.js 540 kB {0} [built]
    [vxCX] ./~/html-webpack-plugin/lib/loader.js!./templates/template.html 1.6 kB {0} [built]
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

C:\winpython-64bit-3.6.x.0\scripts>
````

**Comment by stonebig** [comment]
yet... it seems there is still something not going well with gip:
````
C:\WinPython\basedir35\buildQt5\winpython-32bit-3.5.x.2>if exist "C:\WinPython\basedir35\buildQt5\winpython-32bit-3.5.x.2\python-3.5.4\Lib\site-packages\ipyleaflet" "C:\WinPython\basedir35\buildQt5\winpython-32bit-3.5.x.2\python-3.5.4\Scripts\jupyter.exe" labextension install jupyter-leaflet
> C:\WinPython\basedir35\buildQt5\winpython-32bit-3.5.x.2\python-3.5.4\..\tools\n\npm.CMD pack jupyter-leaflet
jupyter-leaflet-0.5.1.tgz
> node C:\WinPython\basedir35\buildQt5\winpython-32bit-3.5.x.2\python-3.5.4\lib\site-packages\jupyterlab\staging\yarn.js install
yarn install v1.3.2
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.1.3: The platform "win32" is incompatible with this module.
info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "@jupyterlab/vdom-extension > @nteract/transform-vdom@1.1.1" has unmet peer dependency "react@^15.6.1".
warning "@jupyterlab/json-extension > react-highlighter@0.4.2" has unmet peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".
warning "@jupyterlab/json-extension > react-json-tree@0.10.9" has unmet peer dependency "react@^15.0.0".
warning "@jupyterlab/json-extension > react-json-tree@0.10.9" has unmet peer dependency "react-dom@^15.0.0".
[4/4] Building fresh packages...
[1/2] ⠁ canvas: gyp info using node@6.11.5 | win32 | ia32
[2/2] ⠁ jupyter-matplotlib
[-/2] ⠁ waiting...
[-/2] ⠁ waiting...
warning Error running install script for optional dependency: "C:\\\\python-3.5.4\\share\\jupyter\\lab\\staging\\node_modules\\canvas: Command failed.\n
Exit code: 1\n
Command: node-gyp rebuild\n
Arguments: \n
Directory: C:\\\\python-3.5.4\\share\\jupyter\\lab\\staging\\node_modules\\canvas\n
Output:\n
C:\\\\python-3.5.4\\share\\jupyter\\lab\\staging\\node_modules\\canvas>if not defined npm_config_node_gyp (node \"C:\\\\tools\\n\\node_modules\\npm\\bin\\node-gyp-bin\\\\..\\..\\node_modules\\node-gyp\\bin\\node-gyp.js\" rebuild )  else (node \"\" rebuild ) \r\n
gyp info it worked if it ends with ok\ngyp info using node-gyp@3.4.0\ngyp info using node@6.11.5 | win32 | ia32\n
gyp ERR! configure error \n
gyp ERR! stack Error: Python executable \"C:\\\\python-3.5.4\\python.EXE\" is v3.5.4, which is not supported by gyp.\n
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.\n
gyp ERR! stack     at failPythonVersion (C:\\\\tools\\n\\node_modules\\npm\\node_modules\\node-gyp\\lib\\configure.js:454:14)\n
gyp ERR! stack     at C:\\\\tools\\n\\node_modules\\npm\\node_modules\\nodegyp\\lib\\configure.js:443:9\n
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:189:7)\n
gyp ERR! stack     at emitTwo (events.js:106:13)\ngyp ERR! stack     at ChildProcess.emit (events.js:191:7)\n
gyp ERR! stack     at maybeClose (internal/child_process.js:920:16)\n
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)\n
gyp ERR! System Windows_NT 10.0.16299\n
gyp ERR! command \"C:\\\\WinPython\\\\basedir35\\\\buildQt5\\\\winpython-32bit-3.5.x.2\\\\python-3.5.4\\\\..\\\\tools\\\\n\\\\node.exe\" \"C:\\\\WinPython\\\\basedir35\\\\buildQt5\\\\winpython-32bit-3.5.x.2\\\\tools\\\\n\\\\node_modules\\\\npm\\\\node_modules\\\\node-gyp\\\\bin\\\\node-gyp.js\" \"rebuild\"\n
gyp ERR! cwd C:\\WinPytsuccess Saved lockfile.
Done in 59.53s.
> node C:\WinPython\basedir35\buildQt5\winpython-32bit-3.5.x.2\python-3.5.4\lib\site-packages\jupyterlab\staging\yarn.js run build:prod
yarn run v1.3.2
$ webpack --config webpack.prod.config.js
````

**Comment by SylvainCorlay** [comment]
Thanks @stonebig I reopened the issue to keep track on this. I need to put some cycles into ipyleaflet in the next couple of weeks so I will look into this.

**Comment by stonebig** [comment]
"node-gyp" looks to be python-2.7 until its clinical death (https://github.com/nodejs/node-gyp/graphs/contributors). this included battery may never fit

**Comment by blink1073** [comment]
On my phone but note that it says warning, and it is an optional dependency.  You are only seeing this because we can't yet disable trying to install optional dependencies due to a bug in yarn: https://github.com/yarnpkg/yarn/issues/4876

**Comment by blink1073** [comment]
To be clear, this message is known and can be safely ignored.

**Comment by stonebig** [comment]
ok, ipyleaflet works in Jupyterlab with latest release, closing.
