### ISSUE TITLE
jupyter-leaflet, semver range 1.0.0 is not registered as a widget module... due to "fsevent" ?

### ISSUE THREAD

**Issue by stonebig** [ellisonbg/ipyleaflet#95]
on latest jupyterlab-0.31.1, I have this strange error message (on windows10, not anaconda):
- "jupyter-leaflet, semver range 1.0.0 is not registered as a widget module"
- yet, I feel up-to-date seeing "!jupyter labextension list"

What may I miss  ?

![jupyterlabindex4](https://user-images.githubusercontent.com/4312421/34915662-745ad2c4-f92a-11e7-8485-3a6c7afcdec8.PNG)

![jupyterlabindex4b](https://user-images.githubusercontent.com/4312421/34915766-d4599268-f92b-11e7-9045-cd762589607b.PNG)

**Comment by stonebig** [comment]
could the answer be in there ?
````
C:\WinPython\basedir35\buildQt5\winpython-32bit-3.5.x.2>if exist "C:\WinPython\basedir35\buildQt5\winpython-32bit-3.5.x.2\python-3.5.4\Lib\site-packages\ipyleaflet" "C:\WinPython\basedir35\buildQt5\winpython-32bit-3.5.x.2\python-3.5.4\Scripts\jupyter.exe" labextension install jupyter-leaflet
> C:\WinPython\basedir35\buildQt5\winpython-32bit-3.5.x.2\python-3.5.4\..\tools\n\npm.CMD pack jupyter-leaflet
jupyter-leaflet-0.5.1.tgz
> node C:\WinPython\basedir35\buildQt5\winpython-32bit-3.5.x.2\python-3.5.4\lib\site-packages\jupyterlab\staging\yarn.js install
yarn install v1.3.2
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.1.3: The platform "win32" is incompatible with this module.
info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "@jupyterlab/vdom-extension > @nteract/transform-vdom@1.1.1" has unmet peer dependency "react@^15.6.1".
warning "@jupyterlab/json-extension > react-highlighter@0.4.2" has unmet peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".
warning "@jupyterlab/json-extension > react-json-tree@0.10.9" has unmet peer dependency "react@^15.0.0".
warning "@jupyterlab/json-extension > react-json-tree@0.10.9" has unmet peer dependency "react-dom@^15.0.0".
[4/4] Building fresh packages...
[1/2] ⠁ canvas: gyp info using node@6.11.5 | win32 | ia32
[2/2] ⠁ jupyter-matplotlib
[-/2] ⠁ waiting...
[-/2] ⠁ waiting...
warning Error running install script for optional dependency: "C:\\\\python-3.5.4\\share\\jupyter\\lab\\staging\\node_modules\\canvas: Command failed.\n
Exit code: 1\n
Command: node-gyp rebuild\n
Arguments: \n
Directory: C:\\\\python-3.5.4\\share\\jupyter\\lab\\staging\\node_modules\\canvas\n
Output:\n
C:\\\\python-3.5.4\\share\\jupyter\\lab\\staging\\node_modules\\canvas>if not defined npm_config_node_gyp (node \"C:\\\\tools\\n\\node_modules\\npm\\bin\\node-gyp-bin\\\\..\\..\\node_modules\\node-gyp\\bin\\node-gyp.js\" rebuild )  else (node \"\" rebuild ) \r\n
gyp info it worked if it ends with ok\n
gyp info using node-gyp@3.4.0\n
gyp info using node@6.11.5 | win32 | ia32\n
gyp ERR! configure error \n
gyp ERR! stack Error: Python executable \"C:\\\\python-3.5.4\\python.EXE\" is v3.5.4, which is not supported by gyp.\n
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.\n
gyp ERR! stack     at failPythonVersion (C:\\\\tools\\n\\node_modules\\npm\\node_modules\\node-gyp\\lib\\configure.js:454:14)\n
gyp ERR! stack     at C:\\\\tools\\n\\node_modules\\npm\\node_modules\\nodegyp\\lib\\configure.js:443:9\n
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:189:7)\n
gyp ERR! stack     at emitTwo (events.js:106:13)\ngyp ERR! stack     at ChildProcess.emit (events.js:191:7)\n
gyp ERR! stack     at maybeClose (internal/child_process.js:920:16)\n
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)\n
gyp ERR! System Windows_NT 10.0.16299\n
gyp ERR! command \"C:\\\\WinPython\\\\basedir35\\\\buildQt5\\\\winpython-32bit-3.5.x.2\\\\python-3.5.4\\\\..\\\\tools\\\\n\\\\node.exe\" \"C:\\\\WinPython\\\\basedir35\\\\buildQt5\\\\winpython-32bit-3.5.x.2\\\\tools\\\\n\\\\node_modules\\\\npm\\\\node_modules\\\\node-gyp\\\\bin\\\\node-gyp.js\" \"rebuild\"\n
gyp ERR! cwd C:\\WinPytsuccess Saved lockfile.
Done in 59.53s.
> node C:\WinPython\basedir35\buildQt5\winpython-32bit-3.5.x.2\python-3.5.4\lib\site-packages\jupyterlab\staging\yarn.js run build:prod
yarn run v1.3.2
$ webpack --config webpack.prod.config.js
````

**Comment by stonebig** [comment]
it may be related to that https://github.com/nodejs/node-gyp/issues/746 , so my question is rather "how to avoid fsevent problem , to avoid node-gip python-3 problem" ?

**Comment by stonebig** [comment]
ok, I did that:
- install python-2.7 somewhere
- make npm points on it: "npm config set python "C:/somewhere/python-2.7.13/python.exe"
- make node-gyp targets vcbuild 2015: "node-gyp.cmd" configure --msvs_version=2015
- "jupyter lab build"

.... and the result is:
![jupyterlabindex5](https://user-images.githubusercontent.com/4312421/34921074-7efd49ac-f97d-11e7-839c-5e17d1aca904.PNG)

I start to think Jupyterlab is not a maintainable option on Windows 'native', because of node-gyp.

**Comment by SylvainCorlay** [comment]
Reproducing the issue.

**Comment by jasongrout** [comment]
It looks like the issue is that the model and view version numbers are not defined here: https://github.com/ellisonbg/ipyleaflet/blob/master/ipyleaflet/leaflet.py#L566

Here is what it inherited, and what is sent to the frontend:

```
_model_module:"jupyter-leaflet"
_model_module_version:"1.0.0"
_model_name:"LeafletMapModel"
_view_module:"jupyter-leaflet"
_view_module_version:""
_view_name:"LeafletMapView"
```
